### ISSUE TITLE
Rust backend based on nats and redis and crdts

### ISSUE THREAD

**Issue by valdo404** [raphoester/clickplanet.lol-frontend#14]
hi, I have begun a rust fork of your backend and I would like to test its integration with your frontend 

https://github.com/valdo404/clickplanet-rust/pull/2

it is optimised for latency and price and it is gonna use in-memory structures and nats for synchronization. And maybe cloudflare workers but unsure about it.

would you like to talk about it ?

regards,
Laurent

**Comment by raphoester** [comment]
Nice work Laurent !
Let's speak : https://calendly.com/raphaeloester/30

**Comment by valdo404** [comment]
We had a meeting today. Were you available ?

I have tested the server, and it looks like it is rather fast.

I hope I will be able to test it with the frontend soon

**Comment by raphoester** [comment]
not an issue
