### ISSUE TITLE
UI is ugly damn

### ISSUE THREAD

**Issue by raphoester** [raphoester/clickplanet.lol-frontend#4]
Suggestions are open but this is an idea that I received, I think it looks pretty cool 

![image](https://github.com/user-attachments/assets/31ffe7e6-08b0-4a2d-8278-c01ef5077517)

**Comment by SRNV** [comment]
I check what I can do, but I think you should keep the sphere

**Comment by raphoester** [comment]
Please keep discussions in english. 
I feel like it's way too corporate formal as a style, is there something wrong with the screenshot i shared ?

**Comment by SRNV** [comment]
sorry for the french,
nope I just followed the first part of the issue description
`Suggestions are open`

but I think the world map should be clickable at anytime (modals are a bit annoying)

**Comment by SRNV** [comment]
do you want to keep the typo "Luckiest Guy" ?

**Comment by raphoester** [comment]
I like that font but it's not mandatory to keep it if you have a better idea 

Regarding the modals : 
- I think the "About" modal is fine because it's not something you want to keep on the side anyway 
- About updating the country, having it on the sidebar is fine but given its current size, i feel like its appearance has to be minified/simplified first to avoid excessive scrolls

**Comment by raphoester** [comment]
Fixed most of it in #15, closing
